### ISSUE TITLE
Pdisk search bot is not working 

### ISSUE THREAD

**Issue by Pradeep1234a** [AbirHasan2005/PDisk-Videos-Search#3]
Search query is missing [Search query is missing ](Pdiskmoviesearchrobot_bot)

**Comment by sunilroyy007** [comment]
It will give results in your account not whole pdisk lol. If it says that keep movie name after /request 🤦‍♀️🤦‍♀️

**Comment by AbirHasan2005** [comment]
> search bot is not working

Any error?

**Comment by bavabee** [comment]
search bot is not working
