### ISSUE TITLE
New Domain 

### ISSUE THREAD

**Issue by coolboy007** [AbirHasan2005/PDisk-Videos-Search#5]
Bhai pdisk ka new domain add karo CDINK.NET wala domain add karo plz.

**Comment by AbirHasan2005** [comment]
> Bhai pdisk ka new domain add karo CDINK.NET wala domain add karo plz.

Do this --->
https://github.com/AbirHasan2005/PDisk-Videos-Search/issues/4#issuecomment-964961596
